export const QUERYUSERINFO_REQ = 'QUERYUSERINF_REQ';
export const QUERYUSERINFO_SUCCESS = 'QUERYUSERINFO_SUCCESS';
export const QUERYUSERINFO_FAILURE = 'QUERYUSERINFO_FAILURE';
export const QUERYHOMEINFO_REQ = 'QUERYHOMEINFO_REQ';
export const QUERYHOMEINFO_SUCCESS = 'QUERYHOMEINFO_SUCCESS';
export const QUERYHOMEINFO_FAILURE = 'QUERYHOMEINFO_FAILURE';
